Repository edgexfoundry/app-service-configurable, pull requests merged in 2023-09, with the labels that each got.

#591 docs: Update repo links in the readme
  README.md
Labels: documentation

#597 build: Update to latest SDK
  go.mod
  go.sum
Labels: dependencies

#599 ci: add automated release workflow on tag creation
  .github/workflows/release.yml
Labels: ci
